name: Mirror to GitHub.com
on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  mirror:
    environment: github-pages
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror to GitHub.com
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB_COM }}
        run: |
          if git remote get-url githubcom >/dev/null 2>&1; then
            git remote set-url githubcom https://$GH_TOKEN@github.com/currentcrisis123/web-backend.git
          else
            git remote add githubcom https://$GH_TOKEN@github.com/currentcrisis123/web-backend.git
          fi
          git push --force --prune githubcom "refs/heads/*:refs/heads/*" "refs/tags/*:refs/tags/*"
